### ISSUE TITLE
How to implement the ellipse

### ISSUE THREAD

**Issue by xwc520** [ByoxCode/DrawView#10]

**Comment by ByoxCode** [comment]
@xwc520 I'm working on that, please wait...

**Comment by xwc520** [comment]
Elliptical I already know how to do it, thank you

**Comment by xwc520** [comment]
Eraser did not erase, but draw white lines, how to really erase？

**Comment by ByoxCode** [comment]
Don't worry, I'm still working on it...

**Comment by ByoxCode** [comment]
These 2 points are solved, in the next version they will be active

**Comment by xwc520** [comment]
Thank,Looking forward to the next version.

**Comment by ByoxCode** [comment]
Ready!
