### ISSUE TITLE
Bitmap background. 

### ISSUE THREAD

**Issue by jd-alexander** [ByoxCode/DrawView#13]
I have some questions about the functionality where a bitmap is added as a background. 

1) Does the bitmap scale to try and fill the whole screen if the aspect ratio of that bitmap allows ? 

2) Is the bitmap also added to the undo / redo states so that it can be removed if necessary ?

**Comment by ByoxCode** [comment]
Answering your questions...

1. At this moment, the background image only scale centerInside on the DrawView
2. Yes, the background image is added to the undo / redo actions

**Comment by jd-alexander** [comment]
thanks.

**Comment by jd-alexander** [comment]
Last feature request, Could you give the ability to add a bitmap as the background so instead of just passing a file a bitmap can be passed, 
So just allowing the developer to pass the bitmap and the matrix that's being painted, 

where the drawing that's being done on the canvas can be done like so 

touchCanvas.drawBitmap(background, matrix, null);

**Comment by ByoxCode** [comment]
I just finished this modification. I hope it's what you want. It's something like this:

```java
mDrawView.setBackgroundImage(imageFile, BackgroundType.FILE, BackgroundScale.CENTER_CROP);
```

or

```java
mDrawView.setBackgroundImage(imageFile, BackgroundType.BITMAP, matrix);
```

The second parametter, BackgroundType are the nexts ones:

```java
public enum BackgroundType {
    FILE,
    BITMAP,
    BYTES
}
```

oviously, you can send a File, Bitmap or a byte array of image...

**Comment by jd-alexander** [comment]
Okay I am going to check it out? did you commit the code already?

**Comment by jd-alexander** [comment]
Let me know when you push this and release a new version so I can test it out.

**Comment by ByoxCode** [comment]
Yes! I tell you when I push the new version

**Comment by jd-alexander** [comment]
Thanks.

**Comment by ByoxCode** [comment]
A promise is a promise! I push the new version. 

Regards!

**Comment by jd-alexander** [comment]
Awesome. I am going to check it out.
