### ISSUE TITLE
Is blank or empty

### ISSUE THREAD

**Issue by jd-alexander** [ByoxCode/DrawView#14]
is there a method that tells if the canvas is blank or empty? Necessary to know if the view has been edited for auto save features or clearing of previous answers, so it could just be a boolean that's set once the canvas is drawn on or if the history is empty.

**Comment by ByoxCode** [comment]
At the moment, you can use `canUndo();` method... This method returns true if you can undo the last action, if you not have a previous action, it means you have a clear or empty DrawView

**Comment by jd-alexander** [comment]
okay I am gonna fork the library and add a more convenient method to wrap around that and also some other utilities methods that would be good as well. Will let you review once I am done.

**Comment by ByoxCode** [comment]
>.< I already have a method to check this, but this change is in the last version (in that I current working)

**Comment by jd-alexander** [comment]
Ok thanks. I was gonna add a method to set a bitmap to the background instead of setting a file because sometimes I might want to rotate my bitmap or do other transformations and it's easier to handle it outside of the library instead of passing a file so I was going to add that.

**Comment by ByoxCode** [comment]
Ok, thats great, but be careful with the bitmap memory errors

**Comment by jd-alexander** [comment]
Okay I will do that.
