### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by jd-alexander** [ByoxCode/DrawView#15]
I have been testing this library and on some devices I have realized that a lag takes place and the lines end up looking choppy etc. After doing some research I realized that it's a thing with the canvas api and that several things have to be done to make it smoother. Two of them are : 

1) not invalidating the entire screen but only replacing the area that was updated, possibly using a clipRect
 
This is mainly important when drawing using the pen tool.

**Comment by ByoxCode** [comment]
And what is the other thing?

**Comment by jd-alexander** [comment]
Oh the other thing was using thread.sleep to slow down the touch events but that's a bit hacky so i removed it.

**Comment by ByoxCode** [comment]
Ok, I think I already can implement that... I'm not sure if this is that you suggested me, whatever you continue developing your solution and we can review

**Comment by jd-alexander** [comment]
Okay I am planning it out.

**Comment by jd-alexander** [comment]
Okay I saw that you implemented the idea I was going to add so no need for me to add it again, mainly this set of code 

`    if (mDrawMoveHistory.size() > 0) {
            mInvalidateRect = new Rect(
                    (int) (touchX - (mDrawMoveHistory.get(lastMoveIndex).getPaint().getStrokeWidth() * 2)),
                    (int) (touchY - (mDrawMoveHistory.get(lastMoveIndex).getPaint().getStrokeWidth() * 2)),
                    (int) (touchX + (mDrawMoveHistory.get(lastMoveIndex).getPaint().getStrokeWidth() * 2)),
                    (int) (touchY + (mDrawMoveHistory.get(lastMoveIndex).getPaint().getStrokeWidth() * 2)));
        }

        invalidate(mInvalidateRect.left, mInvalidateRect.top, mInvalidateRect.right, mInvalidateRect.bottom);`

**Comment by jd-alexander** [comment]
Really good work @ByoxCode
