### ISSUE TITLE
Example app background picker

### ISSUE THREAD

**Issue by jd-alexander** [ByoxCode/DrawView#16]
I downloaded the example app from the play store and it's not allowing me to add a background, screen just goes white.

**Comment by ByoxCode** [comment]
Yes! It's a permissions error, I'll solved this in next version in playstore

**Comment by ByoxCode** [comment]
No! It isn't permissions error... Can you see the permissions dialog when you select background option in sample app?

**Comment by jd-alexander** [comment]
I am not using it on a device that needs permissions. I am using it on Android 4.4.2

**Comment by ByoxCode** [comment]
Ok, I'll check this asap...

**Comment by ByoxCode** [comment]
I have already check this issue, and it's only when don't have any images in your device. If this is right, it's solved.

**Comment by jd-alexander** [comment]
Ok thanks gonna give it a try.

**Comment by jd-alexander** [comment]
I just tried the app. I noticed one issue where sometimes the pen tool doesn't invalidate fast enough. I know how to fix it though.

**Comment by ByoxCode** [comment]
And what is that fix?

**Comment by jd-alexander** [comment]
You have to populate the invalidate rect when looping over the historical x and y and also invalidate in that for loop.

**Comment by ByoxCode** [comment]
I'll test that. 

Thanks!

**Comment by jd-alexander** [comment]
No problem man.
