### ISSUE TITLE
Draw different shapes e.g. Triangle, Pentagon, Hexagon etc.

### ISSUE THREAD

**Issue by DroidDip** [ByoxCode/DrawView#18]
Great application. But want to draw different shapes like Triangle, Pentagon, Hexagon etc. How to draw such shapes with the help of DrawView.

**Comment by ByoxCode** [comment]
God suggestion, I will keep in mind

**Comment by ByoxCode** [comment]
I currently added a snapshot version with this, please review

**Comment by ByoxCode** [comment]
I added new figures in a snapshot update 1.0.2-SNAPSHOT
