### ISSUE TITLE
X.X.X is not a version and  need to put the curent version  number in read me so that it is easier to find the version  

### ISSUE THREAD

**Issue by subhamdubey** [ByoxCode/DrawView#29]
There is no  description of the version number like other android libraries in read me. Everywhere it is mentioned as X.X.X?

**Comment by ByoxCode** [comment]
In README file is the current version. I don't know why you can't see the versions:

![DrawView](https://img.shields.io/badge/drawview-1.3.1-blue.svg) ![DrawViewSnapshot](https://img.shields.io/badge/snapshot-1.0.0-purple.svg)
