### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by kiaanpillay** [ByoxCode/DrawView#3]

**Comment by kiaanpillay** [comment]
Great lib! Is it possible to change the background to an image or have it transparent instead of white?

**Comment by ByoxCode** [comment]
Hi kiaanpillay! At this moment... no, but is a great suggestion! I will add this functionallity!! Thanks!!!

**Comment by mzander** [comment]
I solved this by loading a background image in an underlaying ImageView.
When the user saves his drawing I merge both Bitmaps and save it.

**Comment by aronysidoro** [comment]
@mzander hey, really cool library! I asked about drawing with images and someone on the Slack AndroidChat recommended your repo and posted a link.

I wanted to ask, you last comment about "loading a background image". Can you add that example? I couldn't find it in the code.

**Comment by ByoxCode** [comment]
Hi @aronysidoro! This is because it's not added to the library. I'll work on that asap. I promise O.o

**Comment by ByoxCode** [comment]
Well... @mzander and @kiaanpillay, I added this funcionality, if you want to use it, please update to version 1.2.0, and I currently working on wiki, but.. for use this functionality, use this code below:

`drawView.setBackgroundImage(fileObject);`

Test and comment...

Regards!!
