### ISSUE TITLE
Possible enchancement - zooming in and out

### ISSUE THREAD

**Issue by kal27** [ByoxCode/DrawView#5]
We could also add an option to zoom in and out

**Comment by ByoxCode** [comment]
Hi kal27!! 

Well, it's sounds great!! I'll add to my TODO list and I'll work with this asap! 

Thanks!

**Comment by kal27** [comment]
That would be great!

**Comment by ByoxCode** [comment]
I upload a new version... this contains beta of the zoom, but without all functionality...

Please stand by... jaja

**Comment by ByoxCode** [comment]
Ready! 

Please check new version

**Comment by jd-alexander** [comment]
@ByoxCode like how this issue has been resolved, where you added the feature, you should close it.

**Comment by ByoxCode** [comment]
Thanks @jd-alexander! I close it right now!
