### ISSUE TITLE
ArrayIndexOutOfBoundsException while drawing

### ISSUE THREAD

**Issue by androidmitry** [ByoxCode/DrawView#7]
`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
       at java.util.ArrayList.get(ArrayList.java:310)
       at com.byox.drawview.views.DrawView.onTouch(DrawView.java:204)
       at android.view.View.dispatchTouchEvent(View.java:9296)`

Its easy to reproduce this issue. While you are drawing before `MotionEvent.ACTION_UP` call method `restartDrawing` this will clear mDrawMoveHistory array and cause a crash.

Possible solution is to implement some kind of state machine which will ignore move event after `restartDrawing` or ignore restart method while drawing or just simply check 
`mDrawMoveHistoryIndex != -1` in `MotionEvent.ACTION_UP` and `MotionEvent.ACTION_MOVE` cases.

**Comment by ByoxCode** [comment]
Thanks for that! Please test the new version 1.2.0 and comment

Regards!

**Comment by androidmitry** [comment]
Now I am using version 1.2.4 and this issue doesn't occur. Thank you for fix.
