### ISSUE TITLE
I found the eraser is in the line drawing, not really clear, this how to solve？ please！！！

### ISSUE THREAD

**Issue by xwc520** [ByoxCode/DrawView#9]

**Comment by ByoxCode** [comment]
Hi @xwc520!! Can you attach some capture? Or can you explain more this issue?

**Comment by xwc520** [comment]
Eraser does not rub, but in the draw line

**Comment by ByoxCode** [comment]
Don't worry, I'm still working on it...

**Comment by ByoxCode** [comment]
Ready!
